export const TORRENT_STATUS_LABELS: Record<string, string> = {
  error: 'Error',
  missingfiles: 'Missing files',
  uploading: 'Seeding',
  pausedup: 'Paused seeding',
  stoppedup: 'Stopped seeding',
  queuedup: 'Queued seeding',
  stalledup: 'Seeding stalled',
  checkingup: 'Checking finished data',
  forcedup: 'Forced seeding',
  allocating: 'Allocating',
  downloading: 'Downloading',
  metadl: 'Downloading metadata',
  forcedmetadl: 'Forced metadata download',
  pauseddl: 'Paused download',
  stoppeddl: 'Stopped download',
  queueddl: 'Queued download',
  stalleddl: 'Download stalled',
  checkingdl: 'Checking incomplete data',
  forceddl: 'Forced download',
  checkingresumedata: 'Checking resume data',
  moving: 'Moving files',
  unknown: 'Unknown',
};

export const TORRENT_STATUS_CLASSES: Record<string, string> = {
  error: 'state-badge state-badge--error',
  missingfiles: 'state-badge state-badge--error',
  uploading: 'state-badge state-badge--done',
  pausedup: 'state-badge state-badge--idle',
  stoppedup: 'state-badge state-badge--idle',
  queuedup: 'state-badge state-badge--idle',
  stalledup: 'state-badge state-badge--idle',
  checkingup: 'state-badge state-badge--running',
  forcedup: 'state-badge state-badge--done',
  allocating: 'state-badge state-badge--running',
  downloading: 'state-badge state-badge--running',
  metadl: 'state-badge state-badge--running',
  forcedmetadl: 'state-badge state-badge--running',
  pauseddl: 'state-badge state-badge--idle',
  stoppeddl: 'state-badge state-badge--idle',
  queueddl: 'state-badge state-badge--idle',
  stalleddl: 'state-badge state-badge--idle',
  checkingdl: 'state-badge state-badge--running',
  forceddl: 'state-badge state-badge--running',
  checkingresumedata: 'state-badge state-badge--idle',
  moving: 'state-badge state-badge--running',
  unknown: 'state-badge state-badge--idle',
};

export const TRACKER_STATUS_LABELS: Record<string, string> = {
  '0': 'Disabled',
  '1': 'Not contacted',
  '2': 'Working',
  '3': 'Updating',
  '4': 'Not working',
  '5': 'Tracker error',
  '6': 'Unreachable',
  disabled: 'Disabled',
  working: 'Working',
  ok: 'Working',
  'updating...': 'Updating',
  updating: 'Updating',
  'not working': 'Not working',
  'not contacted yet': 'Not contacted',
};

export const TRACKER_STATUS_CLASSES: Record<string, string> = {
  '0': 'state-badge state-badge--idle',
  '1': 'state-badge state-badge--idle',
  '2': 'state-badge state-badge--done',
  '3': 'state-badge state-badge--running',
  '4': 'state-badge state-badge--error',
  '5': 'state-badge state-badge--error',
  '6': 'state-badge state-badge--error',
  disabled: 'state-badge state-badge--idle',
  working: 'state-badge state-badge--done',
  ok: 'state-badge state-badge--done',
  'updating...': 'state-badge state-badge--running',
  updating: 'state-badge state-badge--running',
  'not working': 'state-badge state-badge--error',
  'not contacted yet': 'state-badge state-badge--idle',
};
